#ifndef INTERPRETER_CONFIG_H
#define INTERPRETER_CONFIG_H

// above interpreter
#define INTERPRETER_MAX_INSTANCES 3

// interpreter
#define INTERPRETER_MAX_FUNCTIONS 256
#define INTERPRETER_MAX_NAME 256
#define INTERPRETER_MAX_PARAMETERS 128
#define INTERPRETER_MAX_VARIABLES 128
#define INTERPRETER_MAX_PARSED_LINES 2048
#define INTERPRETER_MAX_TOKENS_PER_LINE 64
#define INTERPRETER_MAX_TOKEN_LENGTH 256
#define INTERPRETER_MAX_STACK 46
#define INTERPRETER_MAX_ARRAY_SIZE 4096
#define INTERPRETER_PATH_MAX 256
#define INTERPRETER_MAX_INPUT_LENGTH 256

// parser
#define INTERPRETER_MAX_CODE 16000000

#endif
